name: patinhas_amor
description: Flutter mobile application for Patinhas e Amor NGO - managing animal rescue occurrences and rescued animals.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.0.0


  # Mapas (Gratuitos)
  flutter_map: ^6.1.0
  latlong2: any

  geolocator: ^13.0.0

  # Utilidades
  url_launcher: ^6.3.0
  intl: ^0.19.0
  connectivity_plus: ^6.1.0
  http: ^1.1.0
  flutter_dotenv: ^6.0.0

  # PDF e Impressão
  pdf: ^3.10.7
  printing: ^5.11.1

  # Gerenciamento de Estado e Imagens
  provider: ^6.1.1
  image_picker: ^1.0.7

  # Ícones
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env